from squalchemy import column
from model_base import ModelBaseimport
import sqlalchemy.dialects.postgresql as pg

class Room (ModelBase):
    RoomID = Column(
        pg.BIGINT,
        primary_key=True
        autoincrement=True,
        nullable=False
    )

    RoomType
    Available = Column(pg.BOOLEAN)

    # "RoomID" BIGINT NOT NULL GENERATED BY DEAFULT
    